### PR TITLE
TASK: Enforce unique Form element identifiers

### PR DESCRIPTION
**Pull request by bwaidelich**
Adds a signal/slot to prevent custom Form element identifiers
to be reused.

If an identifier was used in the form already, when the same
identifier is reused it will be suffixed with a counter to ensure
that it is unique.

Resolves: #13

### CODE REVIEW

**Comment by bwaidelich** [comment]
*Note:* To test this you need to run
```
./flow package:rescan
```
in order to have Flow pick up the new `Package` implementation

**Comment by DrillSergeant** [comment]
Tested it. It seems to append "-1" even if the the same identifier was not used before.

**Comment by bwaidelich** [comment]
@DrillSergeant Thanks for the feedback. What a rookie mistake ;) ccaaf72c8a3de329c28af2b4802b00418cfbbaee should fix it

**Comment by DrillSergeant** [comment]
Re-tested and now works as intended.

**Comment by bwaidelich** [comment]
Thanks for testing!

**Pull request merged**
